"""The three field items — the breaths a run finds lying on the floor.

    python3 scripts/field_items.py    # rewrites apps/ss/assets/ss-pickup-{breath,hold,burn}.json

feelers drew these itself, in Graphics calls in its BootScene, as a horseshoe
magnet, a pocket watch and a vial of fire: three objects from a hardware shop
lying in a hive. They are the run's own breaths (the game's names: Deep
Breath, Held Breath, Scent Burn), so they are drawn as what the player
breathes with — organs, the way the food is a nutrient sac and the pulp a
lump of tissue — each in its effect's colour and each with its own idle:

  breath  twin lungs on a short pipe, aqua, swelling and emptying. Taken,
          every lump of pulp on the field is drawn in on the one breath.
  hold    a sealed sac crusted with frost, closed at the top; it does not
          breathe — that is the point — and only the ice on it glints.
          Taken, the horde freezes where it stands.
  burn    a gland like a drop of dark blood, an ember lit inside it and a
          tongue of fire licking out of its tip. Taken, a ring of fire goes
          out of you.

Lit from the upper left like the rest of the roster: the lit side is the
lighter value and the gloss sits up-left. Outlined in $ink at `thin`, the
pickups' own stroke (ss.pickup.food). 24×24, origin at the centre; the
game draws them at the size it drew its own (22–25 px across).
"""
import math, os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from rig import poly, ell, circ, rect, INK_THIN, INK_HAIR, write_doc

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "apps", "ss", "assets")


def part(pid, at, shape, fill, stroke=None, rot=None):
    p = {"id": pid, "at": [round(at[0], 2), round(at[1], 2)]}
    if rot is not None:
        p["rot"] = rot
    p["shape"] = shape
    p["fill"] = fill
    if stroke is not None:
        p["stroke"] = stroke
    return p


def track(pid, prop, keys):
    return {"part": pid, "prop": prop, "keys": [[k, v] for k, v in keys]}


# ================================================================ breath
def breath():
    parts = [
        part("pipe", (0, -7.2), rect(3.2, 6.4, 1.2), "$bone.dark", INK_THIN),
        part("lobe_l", (-3.7, 1.6), ell(5.6, 7.4), "$aqua.dark", INK_THIN, rot=8),
        part("lobe_r", (3.7, 1.6), ell(5.6, 7.4), "$aqua.dark", INK_THIN, rot=-8),
        part("lit_l", (-4.1, 0.9), ell(3.7, 5.3), "$aqua", rot=8),
        part("lit_r", (3.3, 1.9), ell(2.9, 4.4), "$aqua.dark@heavy", rot=-8),
        # Where the pipe forks into the two of them.
        # Where the pipe forks, just above the two of them.
        part("fork", (0, -4.6), poly([(-2.2, 0.9), (-0.7, -0.9), (0.7, -0.9), (2.2, 0.9), (1.5, 1.3), (0, 0.1), (-1.5, 1.3)]), "$bone.dark"),
        part("vein_l", (-4.2, 3.4), poly([(-2.6, -2.4), (-0.4, -0.2), (1.4, 2.6), (0.8, 2.8), (-0.9, 0.4), (-3.0, -1.9)]), "$aqua.dark2"),
        part("vein_r", (4.0, 3.6), poly([(2.6, -2.4), (0.4, -0.2), (-1.4, 2.6), (-0.8, 2.8), (0.9, 0.4), (3.0, -1.9)]), "$aqua.dark2"),
        part("mouth", (0, -10.2), ell(1.5, 0.9), "$ink"),
        part("gloss", (-5.2, -2.6), ell(1.9, 1.0), "$silent@heavy", rot=-34),
    ]
    anims = {
        "idle": {
            "description": "a slow deep breath in, and out",
            "duration": 1.8,
            "tracks": [
                track("lobe_l", "scale", [(0, 1), (0.45, 1.1), (1, 1)]),
                track("lobe_r", "scale", [(0, 1), (0.45, 1.1), (1, 1)]),
                track("lit_l", "scale", [(0, 1), (0.45, 1.14), (1, 1)]),
                track("lit_r", "scale", [(0, 1), (0.45, 1.14), (1, 1)]),
                track("gloss", "opacity", [(0, 0.75), (0.45, 1), (1, 0.75)]),
            ],
        }
    }
    return {
        "id": "ss.pickup.breath",
        "name": "Deep Breath",
        "description": (
            "Deep Breath, a field item: twin lungs on a short pipe, aqua, swelling and emptying. Taken, every lump of "
            "pulp on the field is drawn in on the one breath. Was a horseshoe magnet drawn in the game's own Graphics "
            "calls; this is the organ the effect is. Lit from the upper left, outlined in $ink at thin like the food. "
            "Generated by scripts/field_items.py."
        ),
        "tags": ["pickup"],
        "size": [24, 24],
        "parts": parts,
        "animations": anims,
    }


# ================================================================ hold
def hold():
    shard = lambda s: poly([(0, -2.2 * s), (1.1 * s, 0.6 * s), (0, 1.6 * s), (-1.0 * s, 0.4 * s)])
    parts = [
        part("sac", (0, 1.2), ell(6.8, 8.0), "$frost.dark", INK_THIN),
        part("lit", (-1.0, 0.4), ell(4.6, 6.0), "$frost"),
        # Drawn shut: the top of it puckered into a knot.
        part("knot", (0, -7.0), poly([(-2.6, 1.6), (-1.6, -1.0), (0, -1.9), (1.6, -1.0), (2.6, 1.6), (0, 0.8)]), "$frost.dark2", INK_HAIR),
        part("seam", (0, -3.6), poly([(-3.2, -0.3), (3.2, -0.3), (2.8, 0.4), (-2.8, 0.4)]), "$frost.dark2"),
        # Frost crusted on it, four shards catching the light.
        part("ice_0", (-6.2, -3.6), shard(1.15), "$silent", INK_HAIR, rot=-30),
        part("ice_1", (6.0, -4.8), shard(1.0), "$silent", INK_HAIR, rot=24),
        part("ice_2", (6.6, 4.6), shard(0.85), "$silent", INK_HAIR, rot=150),
        part("ice_3", (-5.6, 6.2), shard(0.9), "$silent", INK_HAIR, rot=-150),
        part("gloss", (-3.4, -2.2), ell(1.8, 1.0), "$silent@heavy", rot=-30),
    ]
    anims = {
        "idle": {
            "description": "held: the sac does not breathe, the frost on it glints in turn",
            "duration": 2.4,
            "tracks": [
                track("ice_0", "opacity", [(0, 1), (0.25, 0.55), (0.5, 1), (1, 1)]),
                track("ice_1", "opacity", [(0, 1), (0.25, 1), (0.5, 0.55), (0.75, 1), (1, 1)]),
                track("ice_2", "opacity", [(0, 1), (0.5, 1), (0.75, 0.55), (1, 1)]),
                track("ice_3", "opacity", [(0, 0.55), (0.25, 1), (0.75, 1), (1, 0.55)]),
            ],
        }
    }
    return {
        "id": "ss.pickup.hold",
        "name": "Held Breath",
        "description": (
            "Held Breath, a field item: a sealed sac crusted with frost, its top puckered shut. It does not breathe — "
            "that is the point — and only the ice on it glints. Taken, the horde freezes where it stands. Was a pocket "
            "watch drawn in the game's own Graphics calls. Lit from the upper left, outlined in $ink at thin. "
            "Generated by scripts/field_items.py."
        ),
        "tags": ["pickup"],
        "size": [24, 24],
        "parts": parts,
        "animations": anims,
    }


# ================================================================ burn
def burn():
    # A drop: a round bottom on a circle about (0, 3), drawn up to a point.
    cx, cy, r = 0.0, 3.0, 6.2
    tip = (0.0, -6.4)
    pts = [tip]
    for i in range(0, 15):
        a = math.radians(-35 + i * (250 / 14))  # from up-right, round the bottom, to up-left
        pts.append((cx + math.cos(a) * r, cy + math.sin(a) * r))
    drop = poly(pts)
    tongue = poly([(0, -6.2), (2.3, -1.6), (1.4, 1.2), (0, 0.4), (-1.6, 1.4), (-2.0, -1.4)])
    tongue_in = poly([(0, -3.6), (1.2, -0.6), (0, 0.6), (-1.1, -0.4)])
    parts = [
        part("drop", (0, 1.6), drop, "$oxblood.light", INK_THIN),
        part("glow", (-0.6, 3.8), ell(4.6, 4.8), "$ember"),
        part("heart", (-0.9, 4.4), ell(2.1, 2.3), "$gold"),
        part("tongue", (0.2, -5.4), tongue, "$ember", INK_HAIR),
        part("tongue_in", (0.2, -4.6), tongue_in, "$gold"),
        part("gloss", (-3.2, 0.2), ell(1.6, 0.9), "$silent@heavy", rot=-50),
    ]
    anims = {
        "idle": {
            "description": "the fire at its tip licking, the ember inside it pulsing",
            "duration": 0.9,
            "tracks": [
                track("tongue", "scale", [(0, 1), (0.3, 1.16), (0.6, 0.9), (1, 1)]),
                track("tongue", "rot", [(0, 0), (0.3, 6), (0.6, -5), (1, 0)]),
                track("tongue_in", "scale", [(0, 1), (0.3, 1.2), (0.6, 0.85), (1, 1)]),
                track("heart", "opacity", [(0, 0.85), (0.4, 1), (1, 0.85)]),
            ],
        }
    }
    return {
        "id": "ss.pickup.burn",
        "name": "Scent Burn",
        "description": (
            "Scent Burn, a field item: a gland like a drop of dark blood, an ember lit inside it and a tongue of fire "
            "licking out of its tip. Taken, a ring of fire goes out of you (ss.fx.flare). Was a vial of fire drawn in "
            "the game's own Graphics calls. Lit from the upper left, outlined in $ink at thin. "
            "Generated by scripts/field_items.py."
        ),
        "tags": ["pickup"],
        "size": [24, 24],
        "parts": parts,
        "animations": anims,
    }


if __name__ == "__main__":
    for doc in (breath(), hold(), burn()):
        path = os.path.join(OUT, doc["id"].replace(".", "-") + ".json")
        write_doc(doc, path)
        print("wrote", os.path.relpath(path))
